=== SolarisPKN/Villars-Informa/.astro/collections/locales.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "nombre": {
      "type": "string"
    },
    "direccion": {
      "type": "string"
    },
    "horarios": {
      "type": "string"
    },
    "telefono": {
      "type": "string"
    },
    "categoria": {
      "type": "string"
    },
    "descripcion_corta": {
      "type": "string"
    },
    "paga": {
      "default": false,
      "type": "boolean"
    },
    "menu": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "fotos": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "portada": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "nombre",
    "direccion",
    "horarios",
    "categoria"
  ]
}

=== SolarisPKN/Villars-Informa/src/content/locales/lubricantes-villars/post.json
{
  "nombre": "Lubricantes Villars",
  "direccion": "Infanta Isabel 76 entre Independencia y Francia",
  "horarios": "Todos los dias de 8:30hs a 14:00hs y de 16:30hs a 20:00hs",
  "telefono": "+541156645422",
  "categoria": "Automotor",
  "descripcion_corta": "Venta de lubricantes y aditivos para el automotor",
  "paga": true,
  "menu": [
    "Aceites",
    "Lamparas",
    "Refrigerantes"
  ],
  "fotos": []
}
